-- Sport-specific skill levels (display + sort_order). profiles.sport_levels JSONB values reference level_key per sport.

create table if not exists public.sport_level_definitions (
  id uuid primary key default gen_random_uuid(),
  sport text not null,
  level_key text not null,
  level_label text not null,
  level_description text,
  sort_order int default 0,
  unique (sport, level_key)
);

insert into public.sport_level_definitions (sport, level_key, level_label, level_description, sort_order) values
('Tennis', 'beginner', 'Beginner', 'Never played or just starting out', 1),
('Tennis', 'usta_2_5', 'USTA 2.5', 'Can sustain short rallies, inconsistent serve', 2),
('Tennis', 'usta_3_0', 'USTA 3.0', 'Consistent rallies, basic technique', 3),
('Tennis', 'usta_3_5', 'USTA 3.5', 'Can play matches, directional control', 4),
('Tennis', 'usta_4_0', 'USTA 4.0', 'All-round game, competitive play', 5),
('Tennis', 'usta_4_5', 'USTA 4.5', 'Heavy topspin, high competitive level', 6),
('Tennis', 'usta_5_0', 'USTA 5.0+', 'Semi-pro or professional level', 7),
('Badminton', 'beginner', 'Beginner', 'Just starting out', 1),
('Badminton', 'casual', 'Casual', 'Basic rallies, inconsistent technique', 2),
('Badminton', 'intermediate', 'Intermediate', 'Singles & doubles, basic tactics', 3),
('Badminton', 'advanced', 'Advanced', 'All-round game, amateur competitions', 4),
('Badminton', 'competitive', 'Competitive', 'Played in formal tournaments', 5),
('Badminton', 'elite', 'Elite', 'Provincial / professional level', 6),
('Pickleball', 'beginner', 'Beginner', 'Just starting out', 1),
('Pickleball', 'dupr_2_0', 'DUPR 2.0–2.5', 'Knows basic rules and shots', 2),
('Pickleball', 'dupr_3_0', 'DUPR 3.0–3.5', 'Consistent shots, understands strategy', 3),
('Pickleball', 'dupr_4_0', 'DUPR 4.0–4.5', 'Strong 3rd-shot attacks', 4),
('Pickleball', 'dupr_5_0', 'DUPR 5.0+', 'Competitive / professional level', 5),
('Golf', 'beginner', 'Beginner', 'Handicap 36+', 1),
('Golf', 'handicap_28_36', 'Handicap 28–36', 'Averaging 5–6 over par per hole', 2),
('Golf', 'handicap_18_27', 'Handicap 18–27', 'Averaging 3–4 over par per hole', 3),
('Golf', 'handicap_10_17', 'Handicap 10–17', 'Averaging 1–2 over par per hole', 4),
('Golf', 'handicap_0_9', 'Handicap 0–9', 'Near scratch level', 5),
('Golf', 'scratch_plus', 'Scratch & Below', 'Elite / professional level', 6),
('Swimming', 'non_swimmer', 'Non-swimmer', 'Cannot swim independently', 1),
('Swimming', '25m', 'Can swim 25m', 'One length of a standard pool', 2),
('Swimming', '50m', 'Can swim 50m', 'Two lengths of a standard pool', 3),
('Swimming', '200m', 'Can swim 200m', 'Basic endurance, stable technique', 4),
('Swimming', '500m_plus', 'Can swim 500m+', 'Endurance training, consistent technique', 5),
('Swimming', 'competitive', 'Competitive', 'Competed in formal swim meets', 6),
('Running', 'beginner', 'Beginner Runner', 'Up to 5km, just starting out', 1),
('Running', '5km', '5km Runner', 'Pace 7–9 min/km', 2),
('Running', '10km', '10km Runner', 'Pace 6–7 min/km', 3),
('Running', 'half_marathon', 'Half Marathon', 'Can complete 21km', 4),
('Running', 'marathon', 'Full Marathon', 'Can complete 42km', 5),
('Running', 'ultra', 'Ultra / Competitive', 'Ultra marathon or competitive runner', 6),
('Ski', 'never', 'Never Skied', 'Zero experience', 1),
('Ski', 'beginner', 'Beginner', 'Snowplow turns, green runs', 2),
('Ski', 'intermediate', 'Intermediate', 'Blue runs, parallel turns', 3),
('Ski', 'advanced', 'Advanced', 'Black diamond runs, stable technique', 4),
('Ski', 'expert', 'Expert', 'Double black diamond, jumps & moguls', 5),
('Snowboard', 'never', 'Never Snowboarded', 'Zero experience', 1),
('Snowboard', 'beginner', 'Beginner', 'Basic directional control, can stop', 2),
('Snowboard', 'intermediate', 'Intermediate', 'Blue runs, stable turns', 3),
('Snowboard', 'advanced', 'Advanced', 'Black diamond runs, basic tricks', 4),
('Snowboard', 'expert', 'Expert', 'Park / competition level', 5),
('Basketball', 'beginner', 'Beginner', 'Just starting out', 1),
('Basketball', 'casual', 'Casual', 'Pickup games, knows basic rules', 2),
('Basketball', 'intermediate', 'Intermediate', 'Consistent technique, half/full court', 3),
('Basketball', 'advanced', 'Advanced', 'Structured training, amateur leagues', 4),
('Basketball', 'competitive', 'Competitive', 'School team / club / semi-pro', 5),
('Football', 'beginner', 'Beginner', 'Just starting out', 1),
('Football', 'casual', 'Casual', 'Pickup games, knows basic rules', 2),
('Football', 'intermediate', 'Intermediate', 'Consistent technique, positional awareness', 3),
('Football', 'advanced', 'Advanced', 'Amateur league level', 4),
('Football', 'competitive', 'Competitive', 'School team / club level', 5),
('TableTennis', 'beginner', 'Beginner', 'Just starting out', 1),
('TableTennis', 'casual', 'Casual', 'Basic rallies', 2),
('TableTennis', 'intermediate', 'Intermediate', 'Forehand attack, backhand push', 3),
('TableTennis', 'advanced', 'Advanced', 'Topspin loops, can compete', 4),
('TableTennis', 'competitive', 'Competitive', 'Played in formal tournaments', 5),
('Yoga', 'beginner', 'Beginner', 'Just started practicing', 1),
('Yoga', 'intermediate', 'Intermediate', 'Consistent basic sequences, good flexibility', 2),
('Yoga', 'advanced', 'Advanced', 'Advanced poses, strong practice', 3),
('Yoga', 'instructor', 'Instructor', 'Certified yoga teacher', 4),
('Fitness', 'beginner', 'Beginner', 'Just started training', 1),
('Fitness', 'intermediate', 'Intermediate', 'Training consistently for 6+ months', 2),
('Fitness', 'advanced', 'Advanced', '2+ years of structured training', 3),
('Fitness', 'competitive', 'Competitive', 'Competed in fitness competitions', 4),
('Cycling', 'casual', 'Casual Rider', 'Occasional rides, under 20km', 1),
('Cycling', '50km', '50km Rider', 'Can ride 50km, avg 20km/h+', 2),
('Cycling', '100km', '100km Rider', 'Century rides, avg 25km/h+', 3),
('Cycling', 'gran_fondo', 'Gran Fondo', '160km+ rides, hill experience', 4),
('Cycling', 'competitive', 'Competitive', 'Road racing / hill climb events', 5),
('Climbing', 'beginner', 'Beginner', 'Indoor bouldering V0–V2', 1),
('Climbing', 'intermediate', 'Intermediate', 'Indoor bouldering V3–V5', 2),
('Climbing', 'advanced', 'Advanced', 'Indoor V6–V8, outdoor experience', 3),
('Climbing', 'expert', 'Expert', 'V9+, outdoor multipitch routes', 4),
('Volleyball', 'beginner', 'Beginner', 'Just starting out', 1),
('Volleyball', 'casual', 'Casual', 'Basic passing and serving', 2),
('Volleyball', 'intermediate', 'Intermediate', 'Consistent technique, positional play', 3),
('Volleyball', 'advanced', 'Advanced', 'Amateur league level', 4),
('Volleyball', 'competitive', 'Competitive', 'School team / club level', 5),
('Baseball', 'beginner', 'Beginner', 'Just starting out with baseball / softball', 1),
('Baseball', 'casual', 'Casual', 'Basic throwing and hitting', 2),
('Baseball', 'intermediate', 'Intermediate', 'Knows rules, can play games', 3),
('Baseball', 'advanced', 'Advanced', 'Strong all-round, amateur league', 4),
('Baseball', 'competitive', 'Competitive', 'Club / competitive level', 5),
('Rugby', 'beginner', 'Beginner', 'Just starting out', 1),
('Rugby', 'casual', 'Casual', 'Knows basic rules and passing', 2),
('Rugby', 'intermediate', 'Intermediate', 'Can play amateur matches', 3),
('Rugby', 'advanced', 'Advanced', 'Strong fitness and technique', 4),
('Rugby', 'competitive', 'Competitive', 'Club / school team level', 5),
('Squash', 'beginner', 'Beginner', 'Just starting out', 1),
('Squash', 'casual', 'Casual', 'Basic rallies', 2),
('Squash', 'intermediate', 'Intermediate', 'Consistent technique', 3),
('Squash', 'advanced', 'Advanced', 'Can compete at club level', 4),
('Squash', 'competitive', 'Competitive', 'Club / competitive level', 5),
('Hockey', 'beginner', 'Beginner', 'New to hockey', 1),
('Hockey', 'casual', 'Casual', 'Can skate and control the puck', 2),
('Hockey', 'intermediate', 'Intermediate', 'Can play pickup games', 3),
('Hockey', 'advanced', 'Advanced', 'Strong all-round game', 4),
('Hockey', 'competitive', 'Competitive', 'Club / league level', 5);

alter table public.sport_level_definitions enable row level security;

create policy "public read sport levels"
  on public.sport_level_definitions
  for select
  using (true);
